server:
  port: 7893
spring:
  application:
    #应用的名称，可选
    name: OA
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/Android?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 500MB
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
  mapper-locations: classpath:mapper/**/*.xml
Constant:
  path: D:\img\
#  baseUrl: http://192.168.1.5:7886/common/upload/
  baseUrl: http://192.168.2.4:7777/common/upload/